### ISSUE TITLE
Dependency on mkisofs not in debianpackage

### ISSUE THREAD

**Issue by raqet** [raqet/acquisition-client#1]
Workaround:
sudo apt-get install genisoimage

Acquisition client generation fails when run in plain install of raqet-client

2016-11-08 10:35:20,202 [main] INFO  Main - Startup thread ended.
Traceback (most recent call last):
  File "/usr/bin/raqet", line 385, in <module>
    main()
  File "/usr/bin/raqet", line 374, in main
    C.CreateISO_config(password,baseurl,clientid,hostname,output)
  File "/usr/bin/raqet", line 175, in CreateISO_config
    process=subprocess.Popen(args,bufsize=-1,cwd=self.tmpdir,stdout=isofile,stderr=stderrfile)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by raqet** [comment]
Accidentally installed old version, this has allready been fixed in 0.2
